import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./components/client-wrapper"; // ✅ Import the wrapper
import { SessionProvider } from "next-auth/react";
import { ModelProvider } from "./context/Context";
import Contentwapper from "./context/Contentwapper"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>

         <ModelProvider>
          <Contentwapper>
        {children}
          </Contentwapper>
      </ModelProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
